### ISSUE TITLE
Support ordered dithering

### ISSUE THREAD

**Issue by haroldo-ok** [haroldo-ok/RgbQuant-SMS.js#2]
RgbQuant doesn't come with any ordered dithers included, but that could be implemented; such kind of dithering would be useful on the tile-based hardware that RgbQuant-SMS targets.

**Comment by leeoniya** [comment]
the algo seems pretty trivial [1]. if you wanted to implement it and pull-request into RgbQuant, it'd be cool.

[1] https://en.wikipedia.org/wiki/Ordered_dithering

**Comment by haroldo-ok** [comment]
Okay, I'll take a shot at it.
Em 23/01/2015 21:24, "Leon Sorokin" notifications@github.com escreveu:
